# Generated by Django 4.2.9 on 2024-02-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='desc',
            new_name='descc',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='img',
            new_name='imgg',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='name',
            new_name='nme',
        ),
    ]
