# Generated by Django 4.2.9 on 2024-02-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_desc_teams_descc_rename_img_teams_imgg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='descc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='imgg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='nme',
            new_name='name',
        ),
    ]
