# Generated by Django 4.2.9 on 2024-02-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_descc_teams_desc_rename_imgg_teams_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='desc',
            new_name='descc',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='img',
            new_name='imgs',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='name',
            new_name='namee',
        ),
    ]
