# Generated by Django 4.2.9 on 2024-02-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_rename_desc_teams_descc_rename_img_teams_imgs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='descc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='imgs',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='namee',
            new_name='name',
        ),
    ]
